#!/bin/bash
OPTIND=2
while getopts :m:d:o:c: flag
do
    case "${flag}" in
	m) META_SERVER_FILE=${OPTARG};;
        d) DATA_SERVER_FILE=${OPTARG};;
	o) OUTPUT_FILE=${OPTARG};;
	c) CLIENT_FILE=${OPTARG};;
    esac
done
echo "DATA_SERVER_FILE=$DATA_SERVER_FILE"
echo "META_SERVER_FILE=$META_SERVER_FILE"
echo "OUTPUT_FILE=$OUTPUT_FILE"
echo "STATUS=$1"

STATUS=$1

if [[ $STATUS != "stop" && $STATUS != "start" ]]; then
	echo "Incorrect argument"
	exit 0
fi

if [[ $SLURM_CLUSTER_NAME == '' ]]; then
	SLURM=0
else
	SLURM=1
fi

if [[ $STATUS = "stop" ]];
then
	readarray -t meta_hosts < $META_SERVER_FILE
	readarray -t data_hosts < $DATA_SERVER_FILE
	echo "# Hercules: Stopping data servers"
	for node in "${data_hosts[@]}"
	do
        	(ssh $node "pkill hercules_server" ) &
	done

	echo "# Hercules: Stopping metadata servers"
	for node in "${meta_hosts[@]}"
	do
	        (ssh $node "pkill hercules_server" ) &
	done
	exit 0
fi


#SETUP
META_PORT=70000
DATA_PORT=80000
MALLEABILITY=0
IMSS_LOWER_BOUND_MALLEABILITY=0
IMSS_UPPER_BOUND_MALLEABILITY=0

H_PATH=$(dirname `pwd`)
H_BUILD_PATH=$H_PATH/build
H_BASH_PATH=$H_PATH/bash
echo "> IMSS_PATH: "$IMSS_PATH

## Uncomment when working in Tucan.
IOR_PATH=/home/software/io500/bin
module unload mpi
module load mpi/mpich3/3.2.1
#module load mpi/openmpi
USE_OPEN_MPI=0

## Uncomment when working in MN4.
#module unload impi
#module load gcc/9.2.0
#module load java/8u131
#module load openmpi/4.1.0
#module load ucx/1.13.1
#module load cmake/3.15.4
#module unload openmpi
#module load impi
#module load ior
#IOR_PATH=/apps/IOR/3.3.0/INTEL/IMPI/bin
#MPI_PATH=/gpfs/apps/MN4/INTEL/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin
#USE_OPEN_MPI=0

## Uncomment when working in Italia cluster.
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/rdma-core/build/lib
#IOR_PATH=/beegfs/home/javier.garciablas/opt/spack/linux-ubuntu20.04-zen/gcc-9.4.0/ior-3.3.0-ssyaxpxjajmhy3v5icfqoo63kaeii6wv/bin
#MPI_PATH=/beegfs/home/javier.garciablas/opt/spack/linux-ubuntu20.04-zen/gcc-9.4.0/openmpi-4.1.3-4bpvwm3lcbftmjki6en35c4i5od6wjbr/bin
#USE_OPEN_MPI=1

## Avaible interfaces in Italia cluster: 'eno2'(tcp), 'ibs1'(tcp), 'lo'(tcp), 'opap6s0:1'(ib)
network_devices_list=all
transports_to_use=all

export UCX_NET_DEVICES=$network_devices_list
export UCX_TLS=$transports_to_use
#export UCX_IB_RCACHE_MAX_REGIONS="262144"
#export UCX_NUM_EPS=24
#export UCX_RCACHE_ENABLE=n
#export UCX_IB_REG_METHODS=direct
#export UCX_RC_VERBS_TIMEOUT=5000000.00us

#IMSS_DEBUG="SLOG_TIME"
IMSS_DEBUG=none
#IMSS_DEBUG="SLOG_LIVE"
#IMSS_DEBUG=all
export IMSS_DEBUG=$IMSS_DEBUG

echo $UCX_NET_DEVICES
echo $UCX_TLS

#echo "##############################"
#lscpu
#free -h
#echo "##############################"

#MAX_CLIENTS_PER_NODE=`lscpu | grep "CPU(s)" | head -n 1 | cut -c 22-`

##set -x
#rm *-2023-03-22.log

#NODES_SUM=$((NUM_METADATA+NUM_DATA+NUM_CLIENT))

# SCRIPT
PWD=`pwd`
#srun -n $NODES_SUM hostname |sort > hostfile
#srun -pernode hostname |sort > hostfile 

#cp hostfile meta_hostfile
#cp hostfile data_hostfile
#cp hostfile client_hostfile

##head -n $NUM_METADATA hostfile > meta_hostfile
##tail -n +$((NUM_METADATA+1)) hostfile | head -n $NUM_DATA > data_hostfile
##tail -n +$((NUM_METADATA+NUM_DATA+1)) hostfile | head -n $NODES_FOR_CLIENTS > client_hostfile

##if [ $SHARED_NODES -eq 1 ]
##then
##	cp data_hostfile client_hostfile
##fi

echo "Slurm=$SLURM"

echo "# Hercules: Running metadata servers"
readarray -t meta_hosts < $META_SERVER_FILE
i=0
for node in "${meta_hosts[@]}"
do
	if [[ $SLURM -eq 0 ]]; then
		(ssh $node "cd $H_BASH_PATH && $H_BUILD_PATH/hercules_server m --server-id=$i --stat-logfile=./metadata --port=$META_PORT --bufsize=0") &
	else
		srun --exclusive --export=ALL -N 1 -n 1 -w $node $H_BUILD_PATH/hercules_server m --server-id=$i --stat-logfile=./metadata --port=$META_PORT --bufsize=0 &
	fi
	i=$(($i+1))
done

sleep 10

echo "# Hercules: Running data servers"
readarray -t data_hosts < $DATA_SERVER_FILE
META_NODE=$(head -n 1 $META_SERVER_FILE)
NUM_METADATA=${#meta_hosts[@]}
NUM_DATA=${#data_hosts[@]}
BLOCK_SIZE=512
STORAGE_SIZE=0
i=0
for node in "${data_hosts[@]}"
do
	if [[ $SLURM -eq 0 ]]; then
	        (ssh $node "cd $H_BASH_PATH && $H_BUILD_PATH/hercules_server d --server-id=$i --imss-uri=imss:// --port=$DATA_PORT --bufsize=0 --stat-host=$META_NODE --stat-port=$META_PORT --num-servers=$NUM_DATA --deploy-hostfile=./data_hostfile --block-size=$BLOCK_SIZE --storage-size=$STORAGE_SIZE") &
	else
		srun --exclusive --export=ALL -N 1 -n 1 -w $node $H_BUILD_PATH/hercules_server m --server-id=$i --stat-logfile=./metadata --port=$META_PORT --bufsize=0 &	
	fi
	i=$(($i+1))
done

sleep 10
